const data = [
  {
    id: 1,
    title: "Adirondack",
    location: "New York",
    type: "LD",
  },
  {
    id: 2,
    title: "Algonquin",
    location: "Ontario",
    type: "LD",
  },
  {
    id: 3,
    title: "Austin",
    location: "Texas",
    type: "LD",
  },
  {
    id: 4,
    title: "Bala",
    location: "Ontario",
    type: "LD",
  },
  {
    id: 5,
    title: "Balsam Lake",
    location: "Wisconsin",
    type: "LD",
  },
  {
    id: 6,
    title: "Bancroft",
    location: "Ontario",
    type: "LD",
  },
  {
    id: 7,
    title: "Banff",
    location: "Alberta",
    type: "LD",
  },
  {
    id: 8,
    title: "Buckhorn",
    location: "Ontario",
    type: "LD",
  },
  {
    id: 9,
    title: "Cultus Lake",
    location: "British Columbia",
    type: "LD",
  },
  {
    id: 10,
    title: "Clear Lake",
    location: "Ontario",
    type: "LD",
  },
  {
    id: 11,
    title: "Blue Mountain",
    location: "Ontario",
    type: "MD",
  },
  {
    id: 12,
    title: "Collingwood",
    location: "Ontario",
    type: "MD",
  },
  {
    id: 13,
    title: "Denver",
    location: "Colorado",
    type: "MD",
  },
  {
    id: 14,
    title: "Fernie",
    location: "British Columbia",
    type: "MD",
  },
  {
    id: 15,
    title: "Gatineau",
    location: "Quebec",
    type: "MD",
  },
  {
    id: 16,
    title: "Hope",
    location: "British COlumbia",
    type: "MD",
  },
  {
    id: 17,
    title: "Invermere",
    location: "British Columbia",
    type: "MD",
  },
  {
    id: 18,
    title: "Kimberley",
    location: "British Columbia",
    type: "MD",
  },
  {
    id: 19,
    title: "Leavenworth",
    location: "Washington",
    type: "MD",
  },
  {
    id: 20,
    title: "Mesa",
    location: "Arizona",
    type: "MD",
  },
  {
    id: 21,
    title: "Allenwood Beach",
    location: "Ontario",
    type: "CD",
  },
  {
    id: 22,
    title: "Anaheim",
    location: "California",
    type: "CD",
  },
  {
    id: 23,
    title: "Balm Beach",
    location: "Ontario",
    type: "CD",
  },
  {
    id: 24,
    title: "Barra de Navidad",
    location: "Jalisco",
    type: "CD",
  },
  {
    id: 25,
    title: "Brackley Beach",
    location: "Prince Edward Island",
    type: "CD",
  },
  {
    id: 26,
    title: "Bradenton",
    location: "Florida",
    type: "CD",
  },
  {
    id: 27,
    title: "Chelem",
    location: "Yucatan",
    type: "CD",
  },
  {
    id: 28,
    title: "Cape May",
    location: "New Jersey",
    type: "CD",
  },
  {
    id: 29,
    title: "Cape Coral",
    location: "Florida",
    type: "CD",
  },
  {
    id: 30,
    title: "Cocoa Beach",
    location: "Florida",
    type: "CD",
  },
  {
    id: 31,
    title: "Bayfield",
    location: "Wisconsin",
    type: "ID",
  },
  {
    // id: 32,
    // title: "Bowen Island",
    // location: "British Columbia",
    // type: "ID",
  },
  {
    id: 32,
    title: "Calgary",
    location: "Alberta",
    type: "ID",
  },
  {
    id: 33,
    title: "Campbell River",
    location: "British Columbia",
    type: "ID",
  },
  {
    id: 34,
    title: "Charleston",
    location: "South Carolina",
    type: "ID",
  },
  {
    id: 35,
    title: "Charlottetown",
    location: "Prince Edward Island",
    type: "ID",
  },
  {
    id: 36,
    title: "Cordova Bay",
    location: "British Columbia",
    type: "ID",
  },
  {
    id: 37,
    title: "Digby",
    location: "Nova Scotia",
    type: "ID",
  },
  {
    id: 38,
    title: "Dunedin",
    location: "Florida",
    type: "ID",
  },
  {
    id: 39,
    title: "Galliano Island",
    location: "British Columbia",
    type: "ID",
  },
  {
    id: 40,
    title: "Birch Bay",
    location: "Washington",
    type: "OD",
  },

  {
    id: 41,
    title: "Chéticamp",
    location: "Nova Scotia",
    type: "OD",
  },
  {
    id: 42,
    title: "Wasagaming",
    location: "Manitoba",
    type: "OD",
  },
  {
    id: 43,
    title: "Disney",
    location: "Oklahoma",
    type: "OD",
  },
  {
    id: 44,
    title: "Golden",
    location: "British Columbia",
    type: "OD",
  },
  {
    id: 45,
    title: "Killarney",
    location: "Ontario",
    type: "OD",
  },
  {
    id: 46,
    title: "Niagara Falls",
    location: "Ontario",
    type: "OD",
  },
  {
    id: 47,
    title: "Palm Springs",
    location: "California",
    type: "OD",
  },
  {
    id: 48,
    title: "Turkey Point",
    location: "Ontario",
    type: "OD",
  },
  {
    id: 49,
    title: "Wateron Park",
    location: "Alberta",
    type: "OD",
  },
  {
    id: 50,
    title: "Amsterdam",
    location: "North Holland",
    type: "PD",
  },
  {
    id: 51,
    title: "Barcelona",
    location: "Catalonia",
    type: "PD",
  },
  {
    id: 52,
    title: "Barrie",
    location: "Ontario",
    type: "PD",
  },
  {
    id: 53,
    title: "Barry's Bay",
    location: "Ontario",
    type: "PD",
  },
  {
    id: 54,
    title: "The Blue Mountains",
    location: "Ontario",
    type: "PD",
  },
  {
    id: 55,
    title: "Boston",
    location: "Massachusetts",
    type: "PD",
  },
  {
    id: 56,
    title: "Calabogie",
    location: "Ontario",
    type: "PD",
  },
  {
    id: 57,
    title: "Sault Ste. Marie",
    location: "Ontario",
    type: "PD",
  },
  {
    id: 58,
    title: "Cancún",
    location: "Quintana Roo",
    type: "PD",
  },
  {
    id: 59,
    title: "Chicago",
    location: "Illinois",
    type: "PD",
  }
];
export default data;
